### PR TITLE
Update keepdir description

### PR DESCRIPTION
**Pull request by mrueg**
The file has a different name.

### CODE REVIEW

**Comment by gktrk** [comment]
PMS doesn't say anything about the `.keep_${CATEGORY}_${PN}-${SLOT%/*}` syntax, it only says `an empty file whose name starts with .keep in that directory`. Should we rather say something like "Create an empty directory which will be preserved by the package manager. This is typically accomplished by inserting an empty file to the directory with the name .keep_${CATEGORY}_${PN}-${SLOT%/*}." ?

**Comment by ulm** [comment]
>>>>> On Mon, 26 Sep 2016, Gokturk Yuksek wrote:

> PMS doesn't say anything about the .keep_${CATEGORY}_${PN}-${SLOT%/*} syntax,
> it only says an empty file whose name starts with .keep in that directory.
> Should we rather say something like "Create an empty directory which will be
> preserved by the package manager. This is typically accomplished by inserting
> an empty file to the directory with the name .keep_${CATEGORY}_${PN}-${SLOT%/
> *}." ?

If there is a file in the dir then the dir isn't empty.
Therefore: s/an empty directory/a directory/

**Comment by mrueg** [comment]
@ulm @gktrk mind to check the wording again? Thanks!

**Comment by gktrk** [comment]
LGTM

**Comment by gktrk** [comment]
Merged with minor punctuation changes (so that we don't have a full stop at the end). Thanks!

**Pull request closed without merging**
